version: "3"
services:
 todo:
  build: .
  image: spring-mongo
  ports:
   - "8080:8080"
  links: 
   - mongodb
  environment:
    spring.data.mongodb.uri: mongodb://mongodb/test
    
    
 mongodb:
  image: mongo
  ports:
   - "27017:27017"
